version: '3.3'
services:
    web:
      build: .
      ports:
        - "8000:80"
      links:
        - mysql
      volumes:
        - .:/code
    mysql:
      image: "mysql:latest"
      volumes:
        - ./mysql:/etc/mysql/conf.d
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD : "yes"
